http://localhost:3000/cursos

###

GET http://localhost:3000/cursos/1



###
PUT http://localhost:3000/cursos/2 HTTP/1.1
content-type: application/json

{
    "nome": "Python"
}

###
DELETE http://localhost:3000/cursos/2

###

GET http://localhost:3000/cursos/2 HTTP/1.1

